title: Maria Victoria Peñas Miro
author: Victoria
email: mpenas@cifpfbmoll.eu
description: > # this means to ignore newlines until "baseurl:"
  Master en SEO Avanzado, Técnico Certificado en AeTM y Cytric Travel & Expense.

# social links
github_username:  victoriapenasmiro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate
